### ISSUE TITLE
Additional feature in path_dropbox_2dii()

### ISSUE THREAD

**Issue by andybue** [2DegreesInvesting/r2dii#1] opened 2019-10-23 11:41 UTC
Thanks for this nice function.

However, integration of the function into current code is tricky.

#Problem Statement

Most of the path variables are defined as the following example:
GIT.PATH <<- paste0(DROPBOX.PATH, "2? Investing Team/People/",USER.NAME2,"/GitHub/")
or
SCENARIO.DATA.PATH <<- paste0(DATA.PATH,"/01_ProcessedData/03_ScenarioData/")

All of the strings end with "/"

however the path_dropbox_2dii() function returns a string without final "/"

> path_dropbox_2dii()
C:/Users/2diiBerlin/Dropbox (2° Investing)
or 
> path_dropbox_2dii("git")
C:/Users/2diiBerlin/Dropbox (2° Investing)/git

even edding an empty string does not add the /
> path_dropbox_2dii("")
C:/Users/2diiBerlin/Dropbox (2° Investing)

So, if I would implement the function in it's current state, i would need to nest it still in a paste0 function. 

# Possible Solutions

1. changing the default of the function
> path_dropbox_2dii("")
C:/Users/2diiBerlin/Dropbox (2° Investing)/

2. Setting the option that adding an empty string adds a /

> path_dropbox_2dii()
C:/Users/2diiBerlin/Dropbox (2° Investing)

but

> path_dropbox_2dii("")
C:/Users/2diiBerlin/Dropbox (2° Investing)/

or adding it as an option

> path_dropbox_2dii("")
C:/Users/2diiBerlin/Dropbox (2° Investing)/

**Comment by maurolepore** [comment] 2019-10-28 11:59
Thanks @andybue, 

All functions that create paths are a thin wrapper around functions in the [fs package}(https://fs.r-lib.org/) which work well in all platforms and don't use trailing "/" by design (https://fs.r-lib.org/#tidy-paths).

If you need a trailing "/", feel free to build on top of `path_dropbox_2dii()`.

r2dii is not designed for compatibility with Reference but for best practices, which in many cases means moving away from Reference (see also https://github.com/2DegreesInvesting/r2dii.utils/issues/6).

Closing now.

**Closed** 2019-10-28 12:00 UTC

**Comment by maurolepore** [comment] 2019-10-28 12:02
BTW, let me say explicitly that I very much welcome this type of discussions, so please continue. And feel free to engage Clare in the conversation.
